In [61]:
import pandas as pd
import numpy as np
# originally designed to parse https://opendata.arcgis.com/datasets/496533836db640bcade61dd9078b0d63_53.csv
csv_filename = 'path/to/some_csv_file.csv'
df = pd.read_csv(csv_filename)
#df.PROPTYPE.unique()
#df.stack().unique()

mes = '\n' + '===  DISCARDED  ==='
print(mes)
for c in pd.unique(df.keys()):
    distinct_list = df[c].unique()
    mes = ' ==> ' + c
    if len(distinct_list) == 1 and str(distinct_list[0]) == 'nan':
        mes = c + ' ==> ' + str(distinct_list[0])
        print(mes)
        # print(distinct_list)

mes = '\n' + '===  UNIQUE VALUES  ==='
print(mes)
for c in pd.unique(df.keys()):
    distinct_list = df[c].unique()
    mes = ' ==> ' + c
    if len(distinct_list) == 1 and str(distinct_list[0]) != 'nan':
        mes = c + ' ==> ' + str(distinct_list[0])
        print(mes)
        # print(distinct_list)

mes = '\n' + '===  LIMITED LIST OF VALUES  ==='
print(mes)
for c in pd.unique(df.keys()):
    distinct_list = df[c].unique()
    mes = ' ==> ' + c
    if 1 < len(distinct_list) <= 20:
        mes = ' ==> ' + c
        print(mes)
        #print(distinct_list)

mes = '\n' + '===  EXTENDED LIST OF VALUES  ==='
print(mes)
for c in pd.unique(df.keys()):
    distinct_list = df[c].unique()
    mes = ' ==> ' + c
    if len(distinct_list) > 20:
        mes = ' ==> ' + c
        print(mes)
        print(distinct_list)




===  DISCARDED  ===
ARN ==> nan
ASRNAME ==> nan
TRIGROUP ==> nan
PHASECYCLE ==> nan
DEEDSTATUS ==> nan
REASONCD ==> nan
TXSALEDESC ==> nan
CY1TXSALE ==> nan
CY2YEAR ==> nan
CY2TXSALE ==> nan
CY2TAX ==> nan
CY2PEN ==> nan
CY2INT ==> nan
CY2FEE ==> nan
CY2TOTDUE ==> nan
CY2COLL ==> nan
CY2BAL ==> nan
CY2CR ==> nan
PY1TXSALE ==> nan
PY2YEAR ==> nan
PY3YEAR ==> nan
PY4YEAR ==> nan
PY5YEAR ==> nan
PY6YEAR ==> nan
PY7YEAR ==> nan
PY8YEAR ==> nan
PY9YEAR ==> nan
PY9BAL ==> nan
PY9CR ==> nan
PY10YEAR ==> nan
PY10TAX ==> nan
PY10PEN ==> nan
PY10INT ==> nan
PY10FEE ==> nan
PY10TOTDUE ==> nan
PY10COLL ==> nan
PY10BAL ==> nan
PY10CR ==> nan

===  UNIQUE VALUES  ===
DELCODE ==> N
EXTRACTDAT ==> 2019-04-06T00:00:00.000Z

===  LIMITED LIST OF VALUES  ===
 ==> PROPTYPE
 ==> SUBNBHD
 ==> PARTPART
 ==> VACLNDUSE
 ==> QDRNTNAME
 ==> HSTDCODE
 ==> CLASSTYPE
 ==> TAXRATE
 ==> MIXEDUSE
 ==> MIX1TXTYPE
 ==> MIX1CLASS
 ==> MIX1RATE
 ==> MIX2TXTYPE
 ==> MIX2CLASS
 ==> MIX2RATE
 ==> PCHILDCODE
 ==> ACCEPTCODE


 ==> NEWTOTAL
[2.5237000e+05 3.6850173e+08 2.4317400e+06 ... 6.0161800e+06 3.3118000e+05
 2.6494000e+05]
 ==> PHASELAND
[2.294300e+05 1.486093e+08 2.210680e+06 ... 2.327280e+06 5.937700e+05
 4.951000e+04]
 ==> PHASEBUILD
[0.0000000e+00 2.1989243e+08 3.8623000e+05 ... 1.8027200e+06 5.5997000e+05
 6.4130000e+04]
 ==> LOWNUMBER
[  nan 3001. 1901. ... 2980. 2978.  874.]
 ==> HIGHNUMBER
[  nan 7815. 1424. ... 3107.  351.  557.]
 ==> STREETNAME
['CALVERT ST' 'CONNECTICUT AVE' nan ... 'MILWAUKEE PL' 'ESTHER PL'
 'MONTEREY LN']
 ==> STREETCODE
[2002 2515 0 ... 6110 3380 6164]
 ==> MIX1LNDPCT
[1.        nan 0.401  0.4368 0.375  0.8656 0.6016 0.761  0.978  0.9338
 0.9766 0.981  0.6945 0.3479 0.5998 0.971  0.4304 0.7527 0.9474 0.9635
 0.5516 0.9088 0.9614 0.9721 0.0403 0.5911 0.74   0.75   0.7502 0.5117
 0.895  0.2543 0.6458 0.5    0.6908 0.3436 0.1698 0.8099 0.4497 0.6661
 0.7667 0.6476 0.6182 0.1705 0.4752 0.5276 0.4281 0.8918 0.5502 0.3333
 0.1355 0.0296 0.7501 0.4639 0.3614 0.3094 0.6667 0.80

 ==> DEEDDATE
[nan '2013-03-05T00:00:00.000Z' '2003-11-14T00:00:00.000Z' ...
 '1993-06-11T00:00:00.000Z' '1991-12-11T00:00:00.000Z'
 '1993-08-17T00:00:00.000Z']
 ==> ASSESSMENT
[   229430 368501730   2210680 ...    279170    217520    229590]
 ==> ANNUALTAX
[    0.    3223.74 10952.5  ...  1045.74   608.84  1233.16]
 ==> DUEDATE1
[      nan 20190331. 20190429. 20190410. 20190413. 20190409. 20190506.
 20190510. 20181015. 20180915. 20190502. 20190424. 20190425. 20190423.
 20190412. 20190418. 20190426. 20190503. 20190408. 20190422. 20190416.
 20190419. 20190405. 20190430. 20190501. 20181108. 20181003. 20190415.
 20190411. 20180927. 20181030. 20190329. 20190508. 20190507. 20181016.
 20190509. 20180930. 20181115. 20190417. 20190327. 20190326. 20181105.
 20190402. 20190228. 20181017. 20190227. 20190403. 20181130. 20181211.
 20180924. 20181101. 20181012. 20180920. 20181126. 20190319. 20190117.
 20181114. 20181212. 20180921. 20190101. 20190404. 20181031. 20181005.
 20180912. 20190116. 20190304

 ==> PY3TAX
[     nan  2983.5  10479.82 ...   633.86   679.84   805.3 ]
 ==> PY3PEN
[   nan 208.88 305.4  ... 327.03  94.36  20.59]
 ==> PY3INT
[   nan 281.99 229.05 ... 327.15 304.53 302.6 ]
 ==> PY3FEE
[      nan    200.      381.5  ...    756.69 108457.2     481.25]
 ==> PY3TOTDUE
[     nan  2983.5  10479.82 ...  1036.56  1215.05  1119.67]
 ==> PY3COLL
[     nan  2983.5  10479.82 ...   574.45   708.13   961.65]
 ==> PY3BAL
[   nan 573.97 975.79 ... 410.01 411.54 226.79]
 ==> PY3CR
[        nan 3.50000e+02 1.40000e-01 ... 8.89508e+03 7.72900e+01
 7.81490e+02]
 ==> PY4TAX
[     nan  2865.2  10275.92 ...   891.92   619.32   789.24]
 ==> PY4PEN
[       nan 1.0000e-02 3.1203e+02 ... 1.2556e+02 7.2480e+01 7.2440e+01]
 ==> PY4INT
[       nan 1.0000e-02 9.5170e+01 ... 3.4912e+02 3.4680e+02 3.5757e+02]
 ==> PY4FEE
[    nan   31.5  1385.16 ...  417.61   38.91 2746.27]
 ==> PY4TOTDUE
[     nan  2865.2  10275.92 ...  1074.24  1143.62  1223.77]
 ==> PY4COLL
[     nan  2865.2  10275.92 ...  1195.

 ==> OWNNAME2
[nan 'JOSHUA M SEGAL' 'DEAN S AQUI' ... 'F M WILLIAMS'
 'ROSSANA G VILLALOBOS' 'LORRAINE E NEWMAN']
